---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: FIX "python-apt must be installed to use check mode. If run normally this module can auto-install it."
  apt:
    name: python-apt
    state: present
    
- name: enable puma
  systemd: name=puma enabled=yes
